"""initial_schema

Revision ID: 52311b962685
Revises: 
Create Date: 2026-08-26 21:00:43.199217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52311b962685'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=False)
    op.create_index(op.f('ix_wallets_is_active'), 'wallets', ['is_active'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('condition_id', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=True),
    sa.Column('market_title', sa.Text(), nullable=True),
    sa.Column('market_slug', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('cur_value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_address'], ['wallets.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_condition_id'), 'positions', ['condition_id'], unique=False)
    op.create_index(op.f('ix_positions_wallet_address'), 'positions', ['wallet_address'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('total_volume_usdc', sa.Float(), nullable=False),
    sa.Column('total_pnl_usdc', sa.Float(), nullable=False),
    sa.Column('total_trades_count', sa.Integer(), nullable=False),
    sa.Column('active_positions_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_address'], ['wallets.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_wallet_address'), 'snapshots', ['wallet_address'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('condition_id', sa.String(length=255), nullable=True),
    sa.Column('asset_id', sa.String(length=255), nullable=True),
    sa.Column('market_title', sa.Text(), nullable=True),
    sa.Column('market_slug', sa.String(length=255), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('usdc_size', sa.Float(), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_read_by_agent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_address'], ['wallets.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_condition_id'), 'trades', ['condition_id'], unique=False)
    op.create_index(op.f('ix_trades_is_read_by_agent'), 'trades', ['is_read_by_agent'], unique=False)
    op.create_index(op.f('ix_trades_traded_at'), 'trades', ['traded_at'], unique=False)
    op.create_index(op.f('ix_trades_transaction_hash'), 'trades', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_trades_wallet_address'), 'trades', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_wallet_address'), table_name='trades')
    op.drop_index(op.f('ix_trades_transaction_hash'), table_name='trades')
    op.drop_index(op.f('ix_trades_traded_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_is_read_by_agent'), table_name='trades')
    op.drop_index(op.f('ix_trades_condition_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_snapshots_wallet_address'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_positions_wallet_address'), table_name='positions')
    op.drop_index(op.f('ix_positions_condition_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_wallets_is_active'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
