"""add_performance_indexes

Revision ID: 53a818f1c2e6
Revises: 52311b962685
Create Date: 2026-09-01 21:34:34.713953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a818f1c2e6'
down_revision: Union[str, Sequence[str], None] = '52311b962685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_positions_condition_value', 'positions', ['condition_id', 'cur_value'], unique=False)
    op.create_index(op.f('ix_positions_cur_value'), 'positions', ['cur_value'], unique=False)
    op.create_index(op.f('ix_positions_updated_at'), 'positions', ['updated_at'], unique=False)
    op.create_index('ix_snapshots_date', 'snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_snapshots_snapshot_date'), 'snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_snapshots_wallet_date', 'snapshots', ['wallet_address', 'snapshot_date'], unique=False)
    op.create_index('ix_trades_condition_traded_at', 'trades', ['condition_id', 'traded_at'], unique=False)
    op.create_index('ix_trades_wallet_traded_at', 'trades', ['wallet_address', 'traded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_wallet_traded_at', table_name='trades')
    op.drop_index('ix_trades_condition_traded_at', table_name='trades')
    op.drop_index('ix_snapshots_wallet_date', table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_snapshot_date'), table_name='snapshots')
    op.drop_index('ix_snapshots_date', table_name='snapshots')
    op.drop_index(op.f('ix_positions_updated_at'), table_name='positions')
    op.drop_index(op.f('ix_positions_cur_value'), table_name='positions')
    op.drop_index('ix_positions_condition_value', table_name='positions')
    # ### end Alembic commands ###
