"""prune_and_unique_snapshots

Revision ID: 6b92c6297f8e
Revises: 53a818f1c2e6
Create Date: 2026-09-02 18:59:20.144630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b92c6297f8e'
down_revision: Union[str, Sequence[str], None] = '53a818f1c2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Prune duplicate old snapshots, keeping only the latest snapshot per wallet
    op.execute("""
        DELETE FROM snapshots
        WHERE id NOT IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY wallet_address ORDER BY snapshot_date DESC) as rn
                FROM snapshots
            ) t WHERE t.rn = 1
        )
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index(op.f('ix_positions_updated_at'), table_name='positions')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_snapshots_snapshot_date'), table_name='snapshots')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_snapshots_wallet_address'), table_name='snapshots')
    except Exception:
        pass
    op.create_index(op.f('ix_snapshots_wallet_address'), 'snapshots', ['wallet_address'], unique=True)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_wallet_address'), table_name='snapshots')
    op.create_index(op.f('ix_snapshots_wallet_address'), 'snapshots', ['wallet_address'], unique=False)
    op.create_index(op.f('ix_snapshots_snapshot_date'), 'snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_positions_updated_at'), 'positions', ['updated_at'], unique=False)
    # ### end Alembic commands ###
